Repository atlp-rwanda/elite-bn-fe, pull requests merged in 2022-08, with the labels that each got.

#15 ch(configure-storybook): Configure storybook for component development
  .babelrc
  .eslintrc.json
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/components/App.js
  src/stories/Button.jsx
  src/stories/Button.stories.jsx
  src/stories/Header.jsx
  src/stories/Header.stories.jsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.jsx
  src/stories/Page.stories.jsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  yarn.lock
Labels: ready for review

#6 chore(codeclimate): add test script
  .DS_Store
  .github/workflows/githubActions.yml
  .gitignore
  .vercel/README.txt
  .vercel/project.json
  README.md
  package.json
  src/components/App.js
  test/client.test.js
Labels: ready for review

#16 ch(set-up-redux): set up redux with toolkit
  package.json
  src/.DS_Store
  src/Views/CounterView.js
  src/dammyNav.js
  src/index.js
  src/redux/counter.js
  src/redux/store.js
  src/routes/index.js
  src/styles/index.css
  src/styles/index.scss
  yarn.lock
Labels: ready for review

#17 fix(pre-commit): Prettier and Eslint configuration
  .babelrc
  .eslintrc.json
  .github/workflows/githubActions.yml
  .husky/pre-commit
  .prettierrc.json
  .storybook/main.js
  .storybook/preview.js
  .vercel/project.json
  README.md
  dist/bundle.js
  dist/index.html
  dist/index_bundle.js
  jest.config.json
  package.json
  src/App.js
  src/Views/CounterView.js
  src/Views/HomeView.js
  src/Views/LoginView.js
  src/components/App.js
  src/dammyNav.js
  src/index.html
  src/index.js
  src/redux/counter.js
  src/redux/store.js
  src/routes/index.js
  src/stories/Button.jsx
  src/stories/Button.stories.jsx
  src/stories/Header.jsx
  src/stories/Header.stories.jsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.jsx
  src/stories/Page.stories.jsx
  src/styles/index.css
  src/styles/index.scss
  src/styles/variables.scss
  test/client.test.js
  webpack.config.js
Labels: ready for review

#19 feat(configure axios): configure axios to call api
  .env.example
  .gitignore
  package.json
  src/components/App.js
  utils/api.js
  yarn.lock
Labels: ready for review

#25 chore(setup-material-UI):Initialize a material UI theme to use for the app
  package.json
  src/App.js
  src/MenuBar/MenuBar.js
  src/Views/ThemeView.js
  src/components/App.js
  src/dammyNav.js
  src/index.html
  src/index.js
  src/routes/index.js
  src/theme/colors.js
  src/theme/theme.js
  utils/api.js
  yarn-error.log
  yarn.lock
Labels: ready for review

#29 fix(axios):fixing issues with webpack dotenv
  package.json
  src/App.js
  src/components/App.js
  webpack.config.js
  yarn-error.log
  yarn.lock
Labels: ready for review

#35 (ft-client-register-barefoot-182201524): Users should be able Signup/…
  jest.config.json
  package.json
  src/App.js
  src/Views/HomeView.js
  src/Views/RegisterView.js
  src/components/App.js
  src/components/Authentications/RegisterUser.js
  src/dammyNav.js
  src/redux/features/registerReducer.js
  src/redux/store.js
  src/routes/index.js
  test/registartion.test.js
  utils/api.js
  webpack.config.js
  yarn.lock
Labels: ready for review

#36 ch(dashboard-view): dashboard landing page
  package.json
  src/Layouts/DashboardLayout.js
  src/MenuBar/MenuBar.js
  src/Views/Dashboard.js
  src/components/Dashboard/DashboardComponent.js
  src/dammyNav.js
  src/routes/index.js
  test/client.test.js
  test/dashboard.test.js
  test/registartion.test.js
  yarn.lock
Labels: ready for review

#28 ft-(user-login): Users should be able to Login to Barefoot Nomad
  .DS_Store
  package.json
  src/.DS_Store
  src/App.js
  src/Views/HomeView.js
  src/Views/LoginView.js
  src/components/.DS_Store
  src/components/Authentications/.DS_Store
  src/components/Authentications/login.js
  src/dammyNav.js
  src/index.js
  src/redux/features/login.js
  src/redux/store.js
  src/routes/index.js
  src/theme/theme.js
  test/login.test.js
  utils/privateRoute.js
  webpack.config.js
  yarn-error.log
  yarn.lock
Labels: ready for review

#40 fix(user-register-token)
  .github/workflows/githubActions.yml
  package.json
  src/Layouts/DashboardLayout.js
  src/Views/LoginView.js
  src/Views/RegisterView.js
  src/components/Authentications/RegisterUser.js
  src/components/Authentications/login.js
  src/components/Dashboard/DashboardComponent.js
  src/dammyNav.js
  src/redux/features/login.js
  src/redux/store.js
  src/routes/index.js
  test/login.test.js
  test/registartion.test.js
  utils/api.js
  utils/privateRoute.js
  webpack.config.js
  yarn.lock
Labels: ready for review

#31 ft(social-auth): Users should be able to Login with Google and Facebook
  package.json
  src/App.js
  src/Views/LoginView.js
  src/components/Authentications/login.js
  utils/privateRoute.js
  webpack.config.js
  yarn-error.log
  yarn.lock
Labels: rebase needed

#30 (ft-client-logout-182201571):Logout Functionality
  jest.config.json
  package.json
  src/MenuBar/MenuBar.js
  src/Views/HomeView.js
  src/components/Authentications/login.js
  src/components/auth/auth.logout.js
  src/dammyNav.js
  src/redux/store.js
  src/routes/index.js
  test/client.test.js
  test/login.test.js
Labels: ready for review

#32 Reset password #182201525
  .gitignore
  dist/index.html
  dist/index_bundle.js
  dist/index_bundle.js.LICENSE.txt
  package.json
  src/Views/HomeView.js
  src/Views/LoginView.js
  src/Views/RegisterView.js
  src/components/Authentications/login.js
  src/components/password/ForgotPassword.js
  src/components/password/ResetPassword.js
  src/routes/index.js
  test/app.test.js
  test/password.test.js
  test/registartion.test.js
  utils/privateRoute.js
  webpack.config.js
  yarn.lock
Labels: ready for review, Changes requested
